### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by tiantangmowang** [phillyx/jscrs#2]
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/zzl/.nvm/versions/node/v14.16.0/lib/node_modules/jscrs/build/lib/formats.js:1:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/zzl/.nvm/versions/node/v14.16.0/lib/node_modules/jscrs/build/lib/options.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

node 14.16.0 formats.js 报错找不到window

**Comment by phillyx** [comment]
fixed
